### ISSUE TITLE
GSA directory of agencies

### ISSUE THREAD

**Issue by JoshData** [unitedstates/orgchart#3]
http://www.usa.gov/directory/federal/index.shtml

**Comment by JoshData** [comment]
Phil Ashlock notes:

http://www.usa.gov/About/developer-resources/federal-agency-directory/index.shtml
http://usa-faq.civicagency.org/api/answers/?topic=Reference+and+General+Government&sub_topic=Agencies

**Comment by philipashlock** [comment]
The later one (http://usa-faq.civicagency.org) is an API i built based on USA.gov's FAQ's XML feed - http://www.usa.gov/About/developer-resources/faqs.shtml 

I'm not sure how often their feed is updated, but I have an SQL dump of it at https://github.com/GSA-OCSIT/usa-faqs/tree/master/sql and a script that cleans up the XML feed at https://github.com/GSA-OCSIT/usa-faqs/blob/master/application/controllers/scraper.php
